import './js/main.js'
import './js/header.js'
import './js/anchor.js'
import './js/form.js'
import './js/modal.js'
import './js/slider.js'
import './js/scroll-up.js'
import './js/tabSec.js'

import '../src/normalize.css'
import './styles/header.css'
import './styles/main.css'
import './styles/about.css'
import './styles/services.css'
import './styles/tab-section.css'
import './styles/footer.css'
import './styles/modal.css'
import './styles/scroll-up.css'
import './styles/slider.css'
import './styles/media.css'


import '../src/main.css'